export const shortsData = [
  {
    id: 1,
    like: "644k",
    comment: "3.3k",
    tag: "the mincecraft rizz a whole movie #rizz",
    name: "@calshrimp",
    profile: "/ShortPage/short-profile-1.jpg",
    video: "/ShortPage/video1.mp4",
    likeIcon: "/ShortPage/like.svg",
    dislike: "/ShortPage/dislike.svg",
    commentIcon: "/ShortPage/comment.svg",
    share: "/ShortPage/share.svg",
    more: "/ShortPage/more.svg",
  },
  {
    id: 2,
    like: "343k",
    comment: "868",
    tag: "200 IQ escape Plan in Gta Rp #shorts #changgang #gtarp",
    name: "Ramme",
    profile: "/ShortPage/short-profile-2.jpg",
    video: "/ShortPage/video2.mp4",
    likeIcon: "/ShortPage/like.svg",
    dislike: "/ShortPage/dislike.svg",
    commentIcon: "/ShortPage/comment.svg",
    share: "/ShortPage/share.svg",
    more: "/ShortPage/more.svg",
  },
  {
    id: 1,
    like: "18k",
    comment: "122",
    tag: "He is Every Asian #standupcomedy #shorts #musicalcomedy #crowdwork #filipino #asian",
    name: "@JRDeGuzman1",
    profile: "/ShortPage/short-profile-3.jpg",
    video: "/ShortPage/video3.mp4",
    likeIcon: "/ShortPage/like.svg",
    dislike: "/ShortPage/dislike.svg",
    commentIcon: "/ShortPage/comment.svg",
    share: "/ShortPage/share.svg",
    more: "/ShortPage/more.svg",
  },
  {
    id: 1,
    like: "2.6M",
    comment: "9.7k",
    tag: "He learned to duplicate coins using a magic trick | Movie title: The Kid Who Would Be King #movie",
    name: "@MovieShorts2424",
    profile: "/ShortPage/short-profile-4.jpg",
    video: "/ShortPage/video4.mp4",
    likeIcon: "/ShortPage/like.svg",
    dislike: "/ShortPage/dislike.svg",
    commentIcon: "/ShortPage/comment.svg",
    share: "/ShortPage/share.svg",
    more: "/ShortPage/more.svg",
  },
  {
    id: 1,
    like: "1.5M",
    comment: "5K",
    tag: "Baby takes his first steps!!! OGshorik? *family #cute",
    name: "@Krysandkareem",
    profile: "/ShortPage/short-profile-5.jpg",
    video: "/ShortPage/video5.mp4",
    likeIcon: "/ShortPage/like.svg",
    dislike: "/ShortPage/dislike.svg",
    commentIcon: "/ShortPage/comment.svg",
    share: "/ShortPage/share.svg",
    more: "/ShortPage/more.svg",
  },
];
