export const subs = [
  {
    id: 1,
    title:
      "Stolen Life: The spirit questor unveils the impostor’s secret! (Weekly Recap HD)",
    channel: "GMA Network",
    watching: "373",
    status: "PREMIERE",
    cover: "/Subs/subs1.jpg",
    profile: "/Subs/channels1_profile.jpg",
    indicator: "/Subs/indicator.svg",
  },
  {
    id: 2,
    title: "Kapamilya Online Live I February 10, 2024",
    channel: "ABS-CBN Entertainment",
    watching: "55K",
    status: "LIVE",
    cover: "/Subs/subs2.jpg",
    profile: "/Subs/channels2_profile.jpg",
    indicator: "/Subs/indicator.svg",
  },
  {
    id: 3,
    title: "Kapuso Stream: February 10, 2024 | Abot Kamay Na Pangarap",
    channel: "GMA Network",
    watching: "64K",
    status: "LIVE",
    cover: "/Subs/subs3.jpg",
    profile: "/Subs/channels1_profile.jpg",
    indicator: "/Subs/indicator.svg",
  },
  {
    id: 4,
    title:
      "Walang Matigas na Pulis sa Matinik na Misis Season 2: Suspendido ang pulis?",
    channel: "GMA Network",
    views: "40 views • ",
    timestamp: "6 minutes ago  ",
    cover: "/Subs/subs4.jpg",
    profile: "/Subs/channels1_profile.jpg",
    duration: "0:15 ",
  },
  {
    id: 5,
    title: "The Iron Heart Full Episode 233 - Part 2/3 | English Subbed",
    channel: "ABS-CBN Entertainment",
    views: "78 views •",
    timestamp: "13 minutes ago",
    cover: "/Subs/subs5.jpg",
    profile: "/Subs/channels2_profile.jpg",
    duratiom: " 9:05",
  },
  {
    id: 6,
    title: "The Iron Heart Full Episode 235 - Part 2/2 | English Subbed",
    channel: "ABS-CBN Entertainment",
    views: "87  views •",
    timestamp: "13 minutes ago",
    cover: "/Subs/subs6.jpg",
    profile: "/Subs/channels2_profile.jpg",
    duration: " &#x2022; 9:15",
  },
];
