export const listButton = [
  "All",
  "Mixes",
  "Music",
  "Philippine Music",
  "Its Showtime",
  "Playlists",
  "Acoustic guitar",
  "Cooking shows",
  "Cooking Science",
  "Kapuso Mo, Jessica Soho",
  "Piano",
  "Soul Music",
  "Freestyle Rap",
  "K-Pop",
  "NBA",
  "Recently uploaded",
  "Watched",
  "New to you",
];

export const videoTemplate = [
  {
    id: 1,
    title: "Aircon Tipid Tips 2024",
    src: "/Video/cover1.jpg",
    profile: "/profile/autria.jpg",
    name: "Oliver Austria",
    totalViews: "31K views",
    ago: "2 days ago",
    duration: "10:34",
  },
  {
    id: 2,
    title: "LIFE BACK HOME IN SYDNEY: finals week, grwm + more!",
    src: "/Video/cover2.jpg",
    profile: "/profile/ashley.jpg",
    name: "Ashley Del Mundo",
    totalViews: "172K views",
    ago: "1 month ago",
    duration: "15:06",
  },
  {
    id: 3,
    title: "AN ACTOR ON OMEGLE? 🙈 | I got too shy to rizz him up 🤣",
    src: "/Video/cover3.jpg",
    profile: "/profile/ironheart.jpg",
    name: "Iron Heart",
    totalViews: "172K views",
    ago: "1 month ago",
    duration: "10:23",
  },
  {
    id: 4,
    title: "Cean Jr. - Binibini (Official Music Video)",
    src: "/Video/cover4.jpg",
    profile: "/profile/cean.jpg",
    name: "Cean Jr.",
    totalViews: "3.5M views",
    ago: "3 years ago",
    duration: "5:29",
  },
  {
    id: 5,
    title: "WE MADE IT - Nik Makino x Flow G (Official Music Video)",
    src: "/Video/cover5.jpg",
    profile: "/profile/makino.jpg",
    name: "Nik Makino",
    totalViews: "19M views",
    ago: "1 month ago",
    duration: "4:10",
  },
  {
    id: 6,
    title: "ELLIE - Alisson Shore feat. Kiyo",
    src: "/Video/cover6.jpg",
    profile: "/profile/alisson.jpg",
    name: "Alisson Shore",
    totalViews: "51K views",
    ago: " 1 month ago",
    duration: "4:46",
  },
  {
    id: 7,
    title: "We're back in BOHOL! | Gabbi Garcia",
    src: "/Video/cover7.jpg",
    profile: "/profile/garcia.jpg",
    name: "Gabbi Garcia",
    totalViews: "580K views",
    ago: "1 year ago",
    duration: "25:54",
  },
  {
    id: 8,
    title: "WINNER WINNER EAR CLEANER",
    src: "/Video/cover8.jpg",
    profile: "/profile/dudut.jpg",
    name: "Dudut",
    totalViews: "157K views",
    ago: "4 days ago",
    duration: "9:34",
  },
  {
    id: 9,
    title: "Singing STATUE to my GF 😘😘😘 ",
    src: "/Video/cover9.jpg",
    profile: "/profile/bading.jpg",
    name: "Guthrie Nikolao Benidic Fragata II",
    totalViews: "1.7M views",
    ago: "10 months ago",
    duration: "4:07",
  },
  {
    id: 10,
    title: "Luxury Van Life In Metro Manila",
    src: "/Video/cover10.jpg",
    profile: "/profile/spart.jpg",
    name: "Spart",
    totalViews: "454K views",
    ago: "8 days ago",
    duration: "19:50",
  },
];

export const shortVideo = [
  "/ShortVideo/video1.jpg",
  "/ShortVideo/video2.jpg",
  "/ShortVideo/video3.png",
  "/ShortVideo/video4.png",
  "/ShortVideo/video5.png",
  "/ShortVideo/video6.png",
  "/ShortVideo/video7.png",
  "/ShortVideo/video8.png",
];
